5/17/2024 Nightly
5/17/2024 Nightly

diff --git a/webdna-base b/webdna-base
--- a/webdna-base
+++ b/webdna-base
@@ -1,41 +1,50 @@
 #!/bin/sh
 
 # Defaults
-SCRIPT_VERSION="v0.4.0-alpha"
+SCRIPT_VERSION="${SCRIPT_VERSION:-v0.4.0-alpha}"
 LOGIT_LOG="${LOGIT_LOG:-webdna_log.txt}"
-WEBDNA_TYPE="${WEBDNA_TYPE:-fcgi}"
+WEBDNA_TYPE="${WEBDNA_TYPE:-FastCGI}"
 WEBDNA_VERSION="${WEBDNA_VERSION:-8.6.5}"
-WEBDNA_URL="${WEBDNA_URL:-https://webdna.us/download}"
+INSTALL_DEPENDENCIES="${INSTALL_DEPENDENCIES:-Yes}"
 
 ## OS Vars
-OS_DISTRIBUTION=
-OS_DISTRIBUTION_FAMILY=
-OS_VERSION=
-OS_VERSION_NAME=
-OS_PACKAGE_MGR=
-OS_PACKAGE_MGR_UPDATE_CMD=
-OS_PACKAGE_MGR_UPGRADE_CMD=
-OS_PACKAGE_MGR_INSTALL_CMD=
-OS_PACKAGE_MGR_REMOVE_CMD=
-OS_PACKAGE_MGR_CLEAN_CMD=
-OS_PACKAGE_MGR_CHECK=
+OS_DISTRIBUTION=""
+OS_DISTRIBUTION_FAMILY=""
+OS_VERSION=""
+OS_VERSION_NAME=""
+OS_PACKAGE_MGR=""
+OS_PACKAGE_MGR_UPDATE_CMD=""
+OS_PACKAGE_MGR_UPGRADE_CMD=""
+OS_PACKAGE_MGR_INSTALL_CMD=""
+OS_PACKAGE_MGR_REMOVE_CMD=""
+OS_PACKAGE_MGR_CLEAN_CMD=""
+OS_PACKAGE_MGR_CHECK=""
 
 ## Error Codes
 ERR_INTERNAL=99
 ERR_OS_NODETECT=100
 ERR_OS_UNSUPPORTED=101
 ERR_DEPENDENCY_INSTALL_FAILED=102
-ERR_FILE_VERIFY_FAILED=103
+
+## Get Script Parameters
+while [[ "$#" -gt 0 ]]
+do
+    case $1 in
+        --type)
+        ;;
+        --version)
+            echo "$SCRIPT_VERSION"
+            exit 0
+        ;;
+    esac
+    shift
+done
 
 ## Predefined Values
 export DEBIAN_FRONTEND=noninteractive
 
 ## 'Touch' Log File
-touch $LOGIT_LOG
-
-#
-# Functions
-#
+touch "$LOGIT_LOG"
 
 ## Logging Function
 log_it() {
@@ -47,34 +56,31 @@ log_it() {
 graceful_exit(){
     # Should We Do Some Internal Error Checking Here?
     log_it "$2"
-    exit $1;
+    exit "$1";
 }
 
 ## Error Exit Function
 err_exit(){
-    graceful_exit $1 "ERROR: $2 Exiting script."
+    graceful_exit "$1" "ERROR: $2 Exiting script."
 }
 
 ## Internal Error Function
 err_internal(){
-    err_exit $ERR_INTERNAL "Internal Error."
+    err_exit "$ERR_INTERNAL" "Internal Error."
 }
 
-#
 # OS Init Functions
 # These functions are used to set and detect a distribution automagically
-#
 
 ## Check OS Distribution
 check_os_distro(){
-
     if [ -f /etc/os-release ]; then
         . /etc/os-release
         OS_DISTRIBUTION=$ID
         OS_VERSION=$VERSION_ID
         OS_VERSION_NAME=$VERSION_CODENAME
     else
-        err_exit $ERR_OS_NODETECT "Can't Determine OS Distribution."
+        err_exit "$ERR_OS_NODETECT" "Can't Determine OS Distribution."
     fi
 
     # Fedora detection needs to be tested!
@@ -153,24 +159,17 @@ check_for_package() {
         log_it "Required package '$1' already installed."
     else
         log_it "Required package '$1' not found."
+        if [ "Yes" = "$INSTALL_DEPENDENCIES" ]; then
+            log_it "Installing package '$1'"
+            eval "$OS_PACKAGE_MGR $ASSUMEYES $OS_PACKAGE_MGR_INSTALL_CMD $1"
+            if eval "$OS_PACKAGE_MGR_CHECK $1"; then
+                log_it "Required package '$1' installed."
+            else
+                log_it "Installing Package '$1' Failed."
+            fi
+        fi
     fi
 }
 
-# Download a file from WebDNA
-download_file() {
-    log_it "Downloading $1 from $WEBDNA_URL"
-    # (Will This Work Cross Platform?)
-    wget "$WEBDNA_URL/$1"
-}
 
-# Verify a file from WebDNA (No Tamperin!)
-verify_file() {
-    log_it "Verifying $1"
-    # Is this always installed?
-    sha256sum "$1"
-    if ! sha256sum -c "${$1_SHA256}"; then 
-        log_it "sha256 Checksum failed for $1"; 
-        err_exit $ERR_FILE_VERIFY_FAILED "Could Not Verify File $1"; 
-    fi
-    log_it "Verified $1"
-}
+
diff --git a/webdna-download b/webdna-download
--- a/webdna-download
+++ b/webdna-download
@@ -1,74 +1,73 @@
 #!/bin/bash
 
+## Defaults
+SCRIPT_VERSION="v0.3.0-alpha"
+
 ## Load Shared header
 . webdna-base
 
-## Load WebDNA Hashes
-. webdna-hashes
-
 ## Script Defaults
-SCRIPT_VERSION="v0.3.0-alpha"
+WEBDNA_URL="${WEBDNA_URL:-https://webdna.us/download}"
 DEPENDENCIES="wget unzip"
 
-## Init The Script
-init_script
+## Error Codes
+ERR_FILE_VERIFY_FAILED=201
 
-## Get Script Parameters
-
-
-
+WEBDNA_TYPE="${WEBDNA_TYPE:-FastCGI}"
 WEBDNA_VERSION="${WEBDNA_VERSION:-8.6.5}"
 WEBDNA_FOLDER="${WEBDNA_FOLDER:-WebDNA-folder-8.6}"
-LINUX_WEBDNA="${LINUX_WEBDNA:-WebDNA-Linux-FastCGI-$WEBDNA_VERSION}"
-ALPINE_WEBDNA="${ALPINE_WEBDNA:-WebDNA-Alpine-FastCGI-$WEBDNA_VERSION}"
+WEBDNA_OS_FLAVOR="${WEBDNA_OS_FLAVOR:-Linux}"
+if [ "alpine" = "$OS_DISTRIBUTION" ]; then WEBDNA_OS_FLAVOR="Alpine"; fi
+WEBDNA="${LINUX_WEBDNA:-WebDNA-$WEBDNA_OS_FLAVOR-$WEBDNA_TYPE-$WEBDNA_VERSION}.zip"
 
-# Begin Downloads
-LOGIT "Downloading version $WEBDNA_VERSION of WebDNA!"
+#
+# Functions
+#
 
-# Check for installed packages
-LOGIT "Checking for required packages..."
-PACKAGE_CHECK "wget"
-PACKAGE_CHECK "unzip"
+## Download a file from WebDNA
+download_file() {
+    log_it "Downloading $1 from $WEBDNA_URL"
+    # (Will This Work Cross Platform?)
+    wget "$WEBDNA_URL/$1"
+}
 
-# Download WebDNA Folder
-LOGIT "Downloading https://webdna.us/download/$WEBDNA_FOLDER.zip"
-wget "https://webdna.us/download/$WEBDNA_FOLDER.zip"
+## Verify a file from WebDNA (No Tamperin!)
+verify_file() {
+    log_it "Verifying $1"
+    # Is this always installed?
+    sha256sum "$1"
+    if ! sha256sum -c "hashes/${1}.sha256"; then 
+        log_it "sha256 Checksum failed for $1"; 
+        err_exit $ERR_FILE_VERIFY_FAILED "Could Not Verify File $1"; 
+    fi
+    log_it "Verified $1"
+}
 
-# Check against hash
-LOGIT "Verifying $WEBDNA_FOLDER.zip"
-sha256sum "$WEBDNA_FOLDER.zip"
-if ! sha256sum -c "hashes/$WEBDNA_FOLDER.zip.sha256"; then LOGIT "sha256 Checksum failed for $WEBDNA_FOLDER.zip" >&2; exit 3; fi
+## Extract Files
+extract_files() {
+    log_it "Extracting $1"
+    unzip -d . "$1"
+    log_it "Clean Up $1"
+    rm -f "$1"
+}
 
-# Extract Archive
-LOGIT "Extracting $WEBDNA_FOLDER.zip"
-unzip -d . "$WEBDNA_FOLDER.zip"
+## Download Packages and 'Install' Them
 
-# Remove Archive
-LOGIT "Removing $WEBDNA_FOLDER.zip"
-rm -f "$WEBDNA_FOLDER.zip"
+## Check dependencies
+check_dependencies() {
+    check_for_package "wget"
+    check_for_package "unzip"
+}
 
-# Downloaded and verified WebDNA Folder
-LOGIT "Downloaded, verified, and extracted $WEBDNA_FOLDER"
+## Download,Verify, Extract
+dve() {
+    download_file "$1"
+    verify_file "$1"
+    extract_files "$1"
+    log_it "Downloaded, verified, and extracted $1"
+}
 
-# Download WebDNA FCGI
-LOGIT "Downloading https://webdna.us/download/$DOWNLOAD_VERSION.zip"
-wget "https://webdna.us/download/$DOWNLOAD_VERSION.zip"
+check_dependencies
 
-# Check against hash
-LOGIT "Verifying $DOWNLOAD_VERSION.zip"
-sha256sum "$DOWNLOAD_VERSION.zip"
-if ! sha256sum -c "hashes/$DOWNLOAD_VERSION.zip.sha256"; then LOGIT "sha256 Checksum failed for $DOWNLOAD_VERSION.zip" >&2; exit 3; fi
-
-# Extract Archive
-LOGIT "Extracting $DOWNLOAD_VERSION.zip"
-unzip -d . "$DOWNLOAD_VERSION.zip"
-
-# Remove Archive
-LOGIT "Removing $DOWNLOAD_VERSION.zip"
-rm -f "$DOWNLOAD_VERSION.zip"
-
-# Downloaded and verified WebDNA Folder
-LOGIT "Downloaded, verified, and extracted $DOWNLOAD_VERSION"
-
-# Check for version and put together the 'correct' WebDNA Folder Structure
-
+dve "$WEBDNA"
+dve "$WEBDNA_FOLDER"
